import Head from 'next/head';
import About from '../components/About';
import Section from '../components/Section';
import Header from '../components/Header';
import Hero from '../components/Hero';

export default function Home() {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Hero />
      <Section id='about' snap='snap-center' header='about'>
        <About />
      </Section>
      <Section id='experience' snap='snap-center' header='experience'>
        <p>Exp</p>
      </Section>
    </div>
  );
}
